name: 'fnbanalytics_warehouse'
version: '1.0.0'
config-version: 2

profile: 'fnbanalytics_warehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"
  - "dbt_modules"

models:
  fnbanalytics_warehouse:
    01bronze:
      +database: nessie
      +schema: fnbanalytics.01bronze
      +materialized: table
    02silver:
      +database: nessie
      +schema: fnbanalytics.02silver
      +materialized: view
    03gold:
      +database: nessie
      +schema: fnbanalytics.03gold
      +materialized: view
