name: 'fnbanalytics_warehouse'
version: '1.0.0'
config-version: 2

profile: 'fnbanalytics_warehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"
  - "dbt_modules"

models:
  fnbanalytics_warehouse:
    01bronze:
      +database: fnbanalytics
      +schema: 01bronze
      +materialized: table
      #+post-hook: "DROP TABLE IF EXISTS {{ this }}"
    02silver:
      +database: fnbanalytics
      +schema: 02silver
      +materialized: view
      #+post-hook: "DROP VIEW IF EXISTS {{ this }}"
    03gold:
      +database: fnbanalytics
      +schema: 03gold
      +materialized: view
      #+post-hook: "DROP VIEW IF EXISTS {{ this }}"