fnbanalytics_warehouse:
  outputs:
    dev:
      dremio_space: nessie
      dremio_space_folder: fnbanalytics.01bronze
      object_storage_path: fnbanalytics.00raw
      object_storage_source: nessie
      password: SecretDataStack5623#
      port: 9047
      software_host: 10.0.0.21
      threads: 1
      type: dremio
      use_ssl: false
      user: mthammu
  target: dev
