fnbanalytics_warehouse:
  target: dev
  outputs:
    dev:
      type: dremio
      threads: 1
      software_host: 10.0.0.21
      port: 9047  # Standard port for Dremio
      user: mthammu
      password: SecretDataStack5623#
      use_ssl: false
      database: fnbanalytics
      schema: 01bronze
      object_storage_source: fnbanalytics_warehouse
      object_storage_path: lakehouse.00raw